version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  migrate:
    build: .
    command: alembic upgrade head
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  test:
    build: .
    command: pytest tests/test_route.py
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  web:
    build: .
    command: python main.py
    volumes:
      - .:/code:cached
    ports:
      - ${PORT_APP}:5002
    env_file:
      - .env
    depends_on:
      - migrate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata: