services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  migrate: &migrate
    build: .
    command: alembic upgrade head
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  web:
    <<: *migrate
    command: python main.py
    ports:
      - ${PORT_APP}:5002

  test:
    <<: *migrate
    command: pytest tests/test_route.py

volumes:
  pgdata: